quarkus:
  application:
    name: book-app
  banner:
    enabled: false
  datasource:
    db-kind: postgresql

"%dev":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgres://localhost:5432/postgres
      username: postgres
      password: postgres
    hibernate-orm:
      database:
        generation: update
      multitenant: car-selling
    http:
      cors:
        ~: true
        methods: GET, POST
        origin: /.*/
    log:
      level: DEBUG
    smallrye-openapi:
      info-title: Car Selling API
      info-version: 1.0.0
      info-contact-name: Gunardy Sutanto

