quarkus:
  application:
    name: book-app
  banner:
    enabled: false

"%dev":
  quarkus:
    datasource:
      db-kind: H2
      jdbc:
        url: jdbc:h2:mem:car-selling
    hibernate-orm:
      database:
        generation: update
    http:
      cors:
        ~: true
        methods: GET, POST
        origin: /.*/
    log:
      level: DEBUG
    smallrye-openapi:
      info-title: Car Selling API
      info-version: 1.0.0
      info-contact-name: Gunardy Sutanto

