quarkus:
  application:
    name: book-app
  banner:
    enabled: false
  datasource:
    db-kind: postgresql

"%dev":
  quarkus:
    flyway:
      migrate-at-start: true
    hibernate-orm:
      database:
        generation: none
    http:
      cors:
        ~: true
        methods: GET, POST
        origin: /.*/
    log:
      level: INFO
    smallrye-openapi:
      info-title: Car Selling API
      info-version: 1.0.0
      info-contact-name: Gunardy Sutanto

"%test":
  quarkus:
    flyway:
      migrate-at-start: true
    hibernate-orm:
      database:
        generation: none
    http:
      cors:
        ~: true
        methods: GET, POST
        origin: /.*/
    log:
      level: INFO
    smallrye-openapi:
      info-title: Car Selling API
      info-version: 1.0.0
      info-contact-name: Gunardy Sutanto
