global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: selling-car-metric
    metrics_path: '/q/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['selling-car-platform:8080']