name: publish-image-to-gcp
on:
  workflow_run:
    types: [completed]
    workflows: [unit-test]
permissions:
  contents: read
  id-token: write

jobs:
  publish-image-to-gcp:
    env:
      region: 'asia-southeast2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Authenticate to Google Cloud
        id: gcp_auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCT }}
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.region }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.access_token }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.region }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker-repo/book-app:latest